name: auth_screens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Carousel/carousel1.jpg
    - Assets/Carousel/carousel2.jpg
    - Assets/Carousel/carousel3.jpg
    - Assets/Carousel/carousel4.jpg
    - Assets/Carousel/carousel5.jpg
    - Assets/Carousel/carousel6.jpg
    - Assets/Carousel/carousel7.jpg
    - Assets/Carousel/carousel8.jpg
    - Assets/Carousel/carousel9.jpg
    - Assets/Categories/Clothing.jpeg
    - Assets/Categories/Cosmetics.jpeg
    - Assets/Categories/Electronic Accessories.jpeg
    - Assets/Categories/Household Products.jpeg
    - Assets/Categories/Female Footwear.jpeg
    - Assets/Categories/Male Footwear.jpeg
    - Assets/Categories/Female Accessories.jpeg
    - Assets/Categories/Male Accessories.jpeg
    - Assets/Categories/Men Clothing.jpeg
    - Assets/Categories/Women Clothing.jpeg
    - Assets/Categories/Smoke.jpeg
    - Assets/Categories/Thrift Store.jpeg
    - Assets/Categories/Furniture.jpeg

